### ISSUE TITLE
Questions about preprocess.py

### ISSUE THREAD

**Issue by yy-KEV1N** [myZeratul/Causal-Debias#1]
Hi，May I ask why the following error pops up when I run preprocess.py? 

Traceback (most recent call last):
  File "preprocess.py", line 103, in <module>
    mean_pooled = torch.avg_pool1d(last_avg.transpose(1, 2), kernel_size=2).squeeze(-1)
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

But when I delete the '.squeeze(-1)' in "last_avg = torch.avg_pool1d(last, kernel_size=last.shape[-1]).squeeze(-1)", it can run again, but the following error is reported when running causal-debias.py?

Traceback (most recent call last):
  File "causal-debias.py", line 738, in <module>
    expand_aug_features = get_expand_festure_list(args, train_features + aug_features_ori , tokenizer, model, device, word_list)
  File "causal-debias.py", line 574, in get_expand_festure_list
    temp_list = get_top_k_features(args, feature, tokenizer, model, device, external_ids_list, embedding)
  File "causal-debias.py", line 606, in get_top_k_features
    max_seq_length = len(external_ids_list[index])
TypeError: only integer tensors of a single element can be converted to an index

**Comment by deep1401** [comment]
Hi, 
I was facing the same issue. What solved the problem for me was to just replace `last_avg.transpose(1, 2)` with `last_avg`. Removing the transpose solves issues in both `preprocess.py` as well as `causal-debias.py`

**Comment by myZeratul** [comment]
Oh, I'm sorry for the mistake in my code. I misunderstood the version to submit. You can refer to @deep1401's solution.

**Comment by fengyx8** [comment]
Hi,
I have encountered the same issue with the provided code. 
Despite attempting the suggested modifications by following @deep1401 , I am still unable to resolve the issue.
I have attempted to fix the code of line 112-113 in file `preprocess.py`, switching by **`deleting squeeze(-1) in line 112`** and **`deleting transpose(1, 2) in line 113`** and **`adding unsqueeze(1) in line 113`**, or modifying them simultaneously, but receiving the following **errors**:

# 1 
> Traceback (most recent call last):
>   File "preprocess.py", line 113, in <module>
>     mean_pooled = torch.avg_pool1d(last_avg, kernel_size=2).squeeze(-1)
> RuntimeError: Expected 3-dimensional tensor, but got 2-dimensional tensor for argument #1 'self' (while checking arguments for avg_pool1d)

# 2 
> Traceback (most recent call last):
>   File "preprocess.py", line 113, in <module>
>     mean_pooled = torch.avg_pool1d(last_avg, kernel_size=2).squeeze(-1)
> RuntimeError: Given input size: (768x1x1). Calculated output size: (768x1x0). Output size is too small

**Comment by deep1401** [comment]
Hi @fengyx8, try to keep the squeeze statements as it is and just remove the transpose and it should work

**Comment by fengyx8** [comment]
Hi, @deep1401 
I attempted to keep the squeeze statements in line 112, and remove the transpose in line 113.
Here's my code:
`112:    last_avg = torch.avg_pool1d(last, kernel_size=last.shape[-1]).squeeze(-1)`
`113:    mean_pooled = torch.avg_pool1d(last_avg, kernel_size=2).squeeze(-1)`

But this modification didn't work for me. 
It seems to be that the shape of `last_avg` is `torch.Size([8, 768])`, which is a 2-dimensional tensor, however, the input for `torch.avg_pool1d` should be a 3-dimensional tensor. 
Thus, I received the following error:

> Traceback (most recent call last):
>   File "preprocess.py", line 113, in <module>
>     mean_pooled = torch.avg_pool1d(last_avg, kernel_size=2).squeeze(-1)
> RuntimeError: Expected 3-dimensional tensor, but got 2-dimensional tensor for argument \#1 'self' (while checking arguments for avg_pool1d)

I'm wondering if it's convenient for you to share your code and data with me. Many thanks to you!

@deep1401 @myZeratul

**Comment by myZeratul** [comment]
Please try the following code.
```
with torch.no_grad():
    output = model(input_ids, input_mask)
    hidden_states = output["hidden_states"]
    last = hidden_states[-1].transpose(1, 2)
    last_avg = torch.avg_pool1d(last, kernel_size=last.shape[-1]).squeeze(-1)  # [batch, 768]
    mean_pooled_array = last_avg.detach().cpu().numpy()
```

**Comment by fengyx8** [comment]
> Please try the following code.
> 
> ```
> with torch.no_grad():
>     output = model(input_ids, input_mask)
>     hidden_states = output["hidden_states"]
>     last = hidden_states[-1].transpose(1, 2)
>     last_avg = torch.avg_pool1d(last, kernel_size=last.shape[-1]).squeeze(-1)  # [batch, 768]
>     mean_pooled_array = last_avg.detach().cpu().numpy()
> ```

Hi, @myZeratul 
I have tried this code, and it produced an `external data` file named as `bert_128.bin`.
However, when I subsequently run the file `causal-debias.py`, I got the following error:

```
Traceback (most recent call last): 
  File "causal-debias.py", line 727, in <module> 
    expand_aug_features = get_expand_festure_list(args, train_features + aug_features_ori , tokenizer, model, device, word_list) 
  File "causal-debias.py", line 574, in get_expand_festure_list 
    temp_list = get_top_k_features(args, feature, tokenizer, model, device, external_ids_list, embedding) 
  File "causal-debias.py", line 601, in get_top_k_features 
    mean_pooled = torch.avg_pool1d(last_avg.transpose(1, 2), kernel_size=2).squeeze(-1) 
IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2) 
```

What should I do next to fix this error? And **would you mind** just **updating your code** (as well as **uploading the indispensable datasets**) of this repository directly, to ensure that your provided code is **executable and correct**?
